version: "3"
services:

  django:
    build:
      context: .
      dockerfile: DjangoDockerfile
    ports:
      - "8000:8000"
    restart: always
    depends_on:
      - celery

  celery:
    build:
      context: .
      dockerfile: CeleryDockerfile
    restart: always
