# Generated by Django 4.0.3 on 2022-04-30 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0008_alter_admin_password_alter_admin_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetsInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sn', models.CharField(max_length=128, verbose_name='序列号')),
                ('ipv4', models.CharField(max_length=256, verbose_name='IPv4地址')),
                ('core_num', models.SmallIntegerField(verbose_name='CPU核心数')),
                ('mem', models.IntegerField(verbose_name='内存')),
                ('disk', models.CharField(max_length=128, verbose_name='硬盘')),
                ('status', models.SmallIntegerField(choices=[(1, 'online'), (2, 'offline')], verbose_name='状态')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('owner', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='app01.userinfo')),
            ],
        ),
    ]
