# Generated by Django 4.0.3 on 2022-04-30 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0009_assetsinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetsinfo',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app01.userinfo'),
        ),
    ]
