# Generated by Django 3.2.13 on 2022-05-28 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0011_passwordmanagement'),
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordManagementRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=1000, verbose_name='url')),
                ('msg', models.CharField(max_length=1000, verbose_name='变更记录')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
        ),
    ]
