# Generated by Django 3.2.13 on 2022-06-06 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0012_passwordmanagementrecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_type', models.SmallIntegerField(choices=[(1, '前端'), (2, '后端'), (3, '联接'), (4, '运维'), (5, '其他')], verbose_name='应用分类')),
                ('app_name', models.CharField(max_length=128, verbose_name='应用名称')),
            ],
        ),
    ]
