# Generated by Django 3.2.13 on 2022-06-07 01:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0013_application'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetsinfo',
            name='app',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app01.application'),
        ),
        migrations.AlterField(
            model_name='assetsinfo',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app01.userinfo'),
        ),
    ]
