# Generated by Django 3.2.13 on 2022-06-13 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0014_auto_20220607_0958'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assetsinfo',
            name='app',
        ),
        migrations.AddField(
            model_name='assetsinfo',
            name='app',
            field=models.ManyToManyField(to='app01.Application'),
        ),
    ]
