# Generated by Django 3.2.13 on 2022-06-16 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0016_auto_20220614_2051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetsinfo',
            name='app',
            field=models.ManyToManyField(blank=True, to='app01.Application'),
        ),
    ]
