# Generated by Django 3.2.13 on 2022-06-24 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0017_alter_assetsinfo_app'),
    ]

    operations = [
        migrations.CreateModel(
            name='LowValueConsumable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512, verbose_name='物品分类')),
                ('brand', models.CharField(max_length=512, verbose_name='品牌名称')),
                ('model', models.CharField(max_length=512, verbose_name='物品型号')),
                ('inventory_quantity', models.IntegerField(verbose_name='库存数量')),
                ('price', models.IntegerField(verbose_name='价格')),
                ('warehouse', models.SmallIntegerField(choices=[(1, '上海仓库'), (2, '杭州仓库'), (3, '深圳仓库')], verbose_name='所在库房')),
                ('barcode', models.CharField(max_length=512, verbose_name='商品条码')),
            ],
        ),
    ]
