# Generated by Django 3.2.13 on 2022-06-25 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0019_auto_20220624_1509'),
    ]

    operations = [
        migrations.CreateModel(
            name='LowValueConsumableRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=512, verbose_name='领用人')),
                ('model', models.CharField(max_length=512, verbose_name='物品名称')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='申请时间')),
            ],
        ),
    ]
